## Part 1: Preprocessing

In [21]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [22]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [23]:
# Create y_df with 'Attrition' and 'Department' columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [24]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Age',
    'BusinessTravel',
    'OverTime',
    'JobRole',
    'JobSatisfaction',
    'WorkLifeBalance',
    'YearsAtCompany',
    'RelationshipSatisfaction',
    'EnvironmentSatisfaction',
    'Education',
    'PerformanceRating',
    'MaritalStatus',
    'TotalWorkingYears',
    'JobInvolvement'
]


# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
print("Data types of X_df columns:")
print(X_df.dtypes)
#print(X_df_numeric.dtypes)


Data types of X_df columns:
Age                          int64
BusinessTravel              object
OverTime                    object
JobRole                     object
JobSatisfaction              int64
WorkLifeBalance              int64
YearsAtCompany               int64
RelationshipSatisfaction     int64
EnvironmentSatisfaction      int64
Education                    int64
PerformanceRating            int64
MaritalStatus               object
TotalWorkingYears            int64
JobInvolvement               int64
dtype: object


In [25]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_df,       # Features
    y_df,          # Target variable
    test_size=0.2,           # 20% for testing
    random_state=42,         # For reproducibility
    stratify=y_df               # To maintain class distribution
)

# Verify the shapes of the splits
print("Shapes of the datasets:")
print(f"X_train: {X_train.shape}")  # Expected: (3448, 15)
print(f"X_test: {X_test.shape}")    # Expected: (861, 15)
print(f"y_train: {y_train.shape}")  # Expected: (3448,)
print(f"y_test: {y_test.shape}")    # Expected: (861,)


Shapes of the datasets:
X_train: (1176, 14)
X_test: (294, 14)
y_train: (1176, 2)
y_test: (294, 2)


In [26]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# Convert categorical variables to numeric using One-Hot Encoding
categorical_cols = ['BusinessTravel', 'OverTime', 'JobRole', 'MaritalStatus', 'Education']
X_train_numeric = pd.get_dummies(X_train, columns=categorical_cols)
X_test_numeric = pd.get_dummies(X_test, columns=categorical_cols)

# Show the first few rows of the updated X_df_numeric
print("First 5 rows of X_df after encoding categorical variables:")
display(X_train_numeric.head())

# Show the data types for X_df_numeric
print("Data types of X_df columns:")
print(X_train_numeric.dtypes)


First 5 rows of X_df after encoding categorical variables:


Age  JobSatisfaction  WorkLifeBalance  YearsAtCompany  \
281    42                3                3              20   
990    33                4                4               5   
369    31                2                3               2   
169    32                3                3               5   
1317   27                4                2               5   

      RelationshipSatisfaction  EnvironmentSatisfaction  PerformanceRating  \
281                          3                        2                  4   
990                          1                        2                  3   
369                          4                        3                  3   
169                          1                        3                  4   
1317                         3                        4                  3   

      TotalWorkingYears  JobInvolvement  BusinessTravel_Non-Travel  ...  \
281                  20               3                      False  ...   
990                   8               3                      False  ...   
369                   3               2                      False  ...   
169                   8               3                      False  ...   
1317                  6               3                      False  ...   

      JobRole_Sales Executive  JobRole_Sales Representative  \
281                      True                         False   
990                      True                         False   
369                     False                         False   
169                     False                         False   
1317                    False                         False   

      MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  \
281                    False                   True                 False   
990                    False                   True                 False   
369                    False                  False                  True   
169                    False                  False                  True   
1317                   False                  False                  True   

      Education_1  Education_2  Education_3  Education_4  Education_5  
281          True        False        False        False        False  
990          True        False        False        False        False  
369         False        False        False         True        False  
169         False        False        False        False         True  
1317        False         True        False        False        False  

[5 rows x 31 columns]

Data types of X_df columns:
Age                                  int64
JobSatisfaction                      int64
WorkLifeBalance                      int64
YearsAtCompany                       int64
RelationshipSatisfaction             int64
EnvironmentSatisfaction              int64
PerformanceRating                    int64
TotalWorkingYears                    int64
JobInvolvement                       int64
BusinessTravel_Non-Travel             bool
BusinessTravel_Travel_Frequently      bool
BusinessTravel_Travel_Rarely          bool
OverTime_No                           bool
OverTime_Yes                          bool
JobRole_Healthcare Representative     bool
JobRole_Human Resources               bool
JobRole_Laboratory Technician         bool
JobRole_Manager                       bool
JobRole_Manufacturing Director        bool
JobRole_Research Director             bool
JobRole_Research Scientist            bool
JobRole_Sales Executive               bool
JobRole_Sales Representati

In [27]:
# Create a StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
display(X_train_numeric.head())
scaler.fit(X_train_numeric)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train_numeric)
X_test_scaled = scaler.transform(X_test_numeric)

# Convert the scaled arrays back to DataFrames with original column names
X_train = pd.DataFrame(X_train_scaled, columns=X_train_numeric.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test_numeric.columns, index=X_test.index)

# (Optional) Display the first few rows of the scaled training data
print("First 5 rows of X_train after scaling:")
display(X_train.head())



Age  JobSatisfaction  WorkLifeBalance  YearsAtCompany  \
281    42                3                3              20   
990    33                4                4               5   
369    31                2                3               2   
169    32                3                3               5   
1317   27                4                2               5   

      RelationshipSatisfaction  EnvironmentSatisfaction  PerformanceRating  \
281                          3                        2                  4   
990                          1                        2                  3   
369                          4                        3                  3   
169                          1                        3                  4   
1317                         3                        4                  3   

      TotalWorkingYears  JobInvolvement  BusinessTravel_Non-Travel  ...  \
281                  20               3                      False  ...   
990                   8               3                      False  ...   
369                   3               2                      False  ...   
169                   8               3                      False  ...   
1317                  6               3                      False  ...   

      JobRole_Sales Executive  JobRole_Sales Representative  \
281                      True                         False   
990                      True                         False   
369                     False                         False   
169                     False                         False   
1317                    False                         False   

      MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  \
281                    False                   True                 False   
990                    False                   True                 False   
369                    False                  False                  True   
169                    False                  False                  True   
1317                   False                  False                  True   

      Education_1  Education_2  Education_3  Education_4  Education_5  
281          True        False        False        False        False  
990          True        False        False        False        False  
369         False        False        False         True        False  
169         False        False        False        False         True  
1317        False         True        False        False        False  

[5 rows x 31 columns]

First 5 rows of X_train after scaling:


Age  JobSatisfaction  WorkLifeBalance  YearsAtCompany  \
281   0.540064         0.264225         0.352952        2.057088   
990  -0.435203         1.170139         1.769578       -0.343642   
369  -0.651929        -0.641689         0.352952       -0.823788   
169  -0.543566         0.264225         0.352952       -0.343642   
1317 -1.085381         1.170139        -1.063674       -0.343642   

      RelationshipSatisfaction  EnvironmentSatisfaction  PerformanceRating  \
281                   0.282471                -0.663420           2.314467   
990                  -1.552810                -0.663420          -0.432065   
369                   1.200112                 0.253363          -0.432065   
169                  -1.552810                 0.253363           2.314467   
1317                  0.282471                 1.170145          -0.432065   

      TotalWorkingYears  JobInvolvement  BusinessTravel_Non-Travel  ...  \
281            1.103189        0.385018                  -0.344869  ...   
990           -0.426405        0.385018                  -0.344869  ...   
369           -1.063735       -1.003881                  -0.344869  ...   
169           -0.426405        0.385018                  -0.344869  ...   
1317          -0.681337        0.385018                  -0.344869  ...   

      JobRole_Sales Executive  JobRole_Sales Representative  \
281                  1.867766                      -0.24188   
990                  1.867766                      -0.24188   
369                 -0.535399                      -0.24188   
169                 -0.535399                      -0.24188   
1317                -0.535399                      -0.24188   

      MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  \
281                -0.535399               1.083399             -0.681548   
990                -0.535399               1.083399             -0.681548   
369                -0.535399              -0.923021              1.467247   
169                -0.535399              -0.923021              1.467247   
1317               -0.535399              -0.923021              1.467247   

      Education_1  Education_2  Education_3  Education_4  Education_5  
281      2.731379    -0.490414    -0.795822    -0.603547    -0.185205  
990      2.731379    -0.490414    -0.795822    -0.603547    -0.185205  
369     -0.366115    -0.490414    -0.795822     1.656871    -0.185205  
169     -0.366115    -0.490414    -0.795822    -0.603547     5.399430  
1317    -0.366115     2.039092    -0.795822    -0.603547    -0.185205  

[5 rows x 31 columns]

In [28]:
# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data

# Transform the 'Department' column in training and testing data
y_train_dept_encoded = department_encoder.transform(y_train[['Department']])
y_test_dept_encoded = department_encoder.transform(y_test[['Department']])


In [29]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data

# Transform the 'Attrition' column in training and testing data
y_train_attrition_encoded = attrition_encoder.transform(y_train[['Attrition']])
y_test_attrition_encoded = attrition_encoder.transform(y_test[['Attrition']])


## Create, Compile, and Train the Model

In [38]:
# Find the number of columns in the X training data
input_dim = X_train.shape[1] # Number of columns/features

# Create the input layer
input_layer = layers.Input(shape=(input_dim,), name="input")

# Create at least two shared layers
shared_layer_1 = layers.Dense(64, activation="relu", name="shared1")(input_layer)
shared_layer_2 = layers.Dense(128, activation="relu", name="shared2")(shared_layer_1)


In [39]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = layers.Dense(32, activation="relu", name="department_hidden")(shared_layer_2)

# Create the output layer
dept_output_layer = layers.Dense(2, activation="softmax", name="department_output")(dept_hidden_layer)


In [40]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = layers.Dense(32, activation="relu", name="attrition_hidden")(shared_layer_2)

# Create the output layer
attrition_output_layer = layers.Dense(3, activation="softmax", name="attrition_output")(attrition_hidden_layer)


In [41]:
# Create the model
#model = Model(inputs=input_layer, outputs=[dept_output_layer, attrition_output_layer])
model = Model(inputs=input_layer, outputs=[dept_output_layer, attrition_output_layer])
# Compile the model
model.compile(
    optimizer="adam",
    loss={
        "department_output": "categorical_crossentropy",
        "attrition_output": "categorical_crossentropy"  # Changed from 'binary_crossentropy'
    },
    metrics={
        "department_output": "accuracy",
        "attrition_output": "accuracy"
    }
)

# Summarize the model
model.summary()


Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 31)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │      2,048 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 2)         │         66 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 18,756 (73.27 KB)

 Trainable params: 18,756 (73.27 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
print("Shapes of the datasets:")
print(f"X_train: {X_train.shape}")
print(f"y_train_dept_encoded: {y_train_dept_encoded.shape}")
print(f"y_train_attrition_encoded: {y_train_attrition_encoded.shape}")
print(f"X_test: {X_test.shape}")
print(f"y_test_dept_encoded: {y_test_dept_encoded.shape}")
print(f"y_test_attrition_encoded: {y_test_attrition_encoded.shape}")

print(f"Shape of y_train_dept_encoded: {y_train_dept_encoded.shape}")
print(f"Shape of y_train_attrition_encoded: {y_train_attrition_encoded.shape}")
print("Model output names:", model.output_names)


Shapes of the datasets:
X_train: (1176, 31)
y_train_dept_encoded: (1176, 3)
y_train_attrition_encoded: (1176, 2)
X_test: (294, 31)
y_test_dept_encoded: (294, 3)
y_test_attrition_encoded: (294, 2)
Shape of y_train_dept_encoded: (1176, 3)
Shape of y_train_attrition_encoded: (1176, 2)
Model output names: ListWrapper(['department_output', 'attrition_output'])


In [44]:
print("y_train_dept_encoded (first 5 rows):\n", y_train_dept_encoded[:5])
print("y_train_attrition_encoded (first 5 rows):\n", y_train_attrition_encoded[:5])
print("y_test_dept_encoded (first 5 rows):\n", y_test_dept_encoded[:5])
print("y_test_attrition_encoded (first 5 rows):\n", y_test_attrition_encoded[:5])

history = model.fit(
    X_train,
    {
        "department_output": y_train_dept_encoded,
        "attrition_output": y_train_attrition_encoded
    },
    epochs=20,
    batch_size=32,
    validation_data=(
        X_test,
        {
            "department_output": y_test_dept_encoded,
            "attrition_output": y_test_attrition_encoded
        }
    )
)


y_train_dept_encoded (first 5 rows):
 [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
y_train_attrition_encoded (first 5 rows):
 [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
y_test_dept_encoded (first 5 rows):
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
y_test_attrition_encoded (first 5 rows):
 [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
Epoch 1/20


AttributeError: 'NoneType' object has no attribute 'items'

In [17]:
# Evaluate the model with the testing data

test_results = model.evaluate(

    X_test,

    {

        "department_output": y_test_dept_encoded,

        "attrition_output": y_test_attrition_encoded

    },

    verbose=1  # Set to 1 to see the progress bar

)

print(test_results)

12/12 [==============================] - 0s 3ms/step - loss: 4.1624 - department_output_loss: 3.1143 - attrition_output_loss: 1.0481 - department_output_accuracy: 0.5272 - attrition_output_accuracy: 0.8261


[4.162380218505859,
 3.114327907562256,
 1.0480519533157349,
 0.5271739363670349,
 0.8260869383811951]

In [18]:
# Print the accuracy for both department and attrition

# Retrieve metric names

metric_names = model.metrics_names

print("Metrics Names:", model.metrics_names)

 

# Combine metric names and results into a dictionary

results_dict = dict(zip(metric_names, test_results))

print(results_dict)

# Extract accuracy values

department_accuracy = results_dict['department_output_accuracy']

attrition_accuracy = results_dict['attrition_output_accuracy']

 

# Print the accuracies

print(f"Department predictions accuracy: {department_accuracy}")

print(f"Attrition predictions accuracy: {attrition_accuracy}")


Department predictions accuracy: 0.5271739363670349
Attrition predictions accuracy: 0.8260869383811951


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is a good metric for balanced datasets where all errors have equal costs, but it's not ideal for imbalanced datasets or when false positives and false negatives carry different consequences. In such cases, alternative metrics like precision, recall, F1-score, or ROC-AUC provide more insight by focusing on specific types of errors, especially when detecting minority classes or when the cost of mistakes differs significantly.
2. I used "sofmax" for my output layer because this allows the model to predict the most likely class by assigning higher probabilities to the correct class, which is essential when dealing with more than two classes. The probabilistic output also makes it compatible with loss functions like categorical cross-entropy.
3.  Evaluate with Additional Metrics, Cross-Validation